[package]
name = "ant_viz"
version = "0.1.0"
authors = ["Adolfo Ochagavía <aochagavia92@gmail.com>"]

[dependencies]
ant_lib = { path = "../ant_lib" }
piston_window = "0.63.0"
piston2d-opengl_graphics = "0.39.0"
